MezunBilgiSistemiBitirme/Controllers/FakulteController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MezunBilgiSistemiBitirme.Controllers
{
    public class FakulteController : Controller
    {
        FakulteManager fm = new FakulteManager(new EfFakulteDal());

        public ActionResult Index()
        {
            var FakulteValues = fm.GetList();
            return View(FakulteValues);
        }
        [HttpGet]
        public ActionResult AddFakulte()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddFakulte(Fakulte p)
        {
            FakulteValidator fakulteValidator = new FakulteValidator();
            ValidationResult results = fakulteValidator.Validate(p);
            if (results.IsValid)
            {
                fm.FakulteAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult DeleteFakulte(int id)
        {
            var fakulteValue = fm.GetById(id);
            fm.FakulteDelete(fakulteValue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UpdateFakulte(int id)
        {
            var fakulteValue=fm.GetById(id);
            return View(fakulteValue);
        }

        [HttpPost]
        public ActionResult UpdateFakulte(Fakulte p)
        {
            fm.FakulteUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

MezunBilgiSistemiBitirme/Views/Fakulte/AddFakulte.cshtml
@model EntityLayer.Fakulte
@{
    ViewBag.Title = "AddFakulte";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>Yeni Fakülte Ekleme</h2>
<br />
@using (Html.BeginForm("AddFakulte", "Fakulte", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Fakülte Adı")
        @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ad)
        <br /><br />
        @Html.Label("Adres")
        @Html.TextBoxFor(x => x.adres, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.adres)
        <br /><br />
        @Html.Label("Telefon")
        @Html.TextBoxFor(x => x.tel, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.tel)
        <br /><br />
        @Html.Label("Mail")
        @Html.TextBoxFor(x => x.mail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.mail)
        <br /><br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

MezunBilgiSistemiBitirme/Views/Fakulte/Index.cshtml
@using EntityLayer.Concrete
@model List<EntityLayer.Fakulte>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Fakülte</h2>

<br />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Fakülte Adı</th>
        <th>Fakülte Adresi</th>
        <th>Fakülte Telefonu</th>
        <th>Mail</th>
        <th>Sil</th>
        <th>Güncelle</th>
        @*<th>Bölümler</th>*@
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.fakulteId</th>
            <td>@item.ad</td>
            <td>@item.adres</td>
            <td>@item.tel</td>
            <td>@item.mail</td>
            <td><a href="/Fakulte/DeleteFakulte/@item.fakulteId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Fakulte/UpdateFakulte/@item.fakulteId" class="btn btn-warning">Güncelle</a></td>
            @*<td><a href="#" class="btn btn-primary">Bölümler</a></td>*@
        </tr>
    }
</table>
<br />
<a href="/Fakulte/AddFakulte" class="btn btn-info">Yeni Fakülte</a>

MezunBilgiSistemiBitirme/Views/Fakulte/UpdateFakulte.cshtml
@model EntityLayer.Fakulte

@{
    ViewBag.Title = "UpdateFakulte";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Fakülte Güncelleme</h2>
@using (Html.BeginForm("UpdateFakulte", "Fakulte", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.Label("ID")
                    @Html.TextBoxFor(x => x.fakulteId, new {@class = "form-control"})
                    <br />
                    @Html.Label("Fakülte Adı")
                    @Html.TextBoxFor(x => x.ad, new { @class = "form-control"})
                    <br />
                    @Html.Label("Adres")
                    @Html.TextBoxFor(x => x.adres, new { @class = "form-control" })
                    <br />
                    @Html.Label("Telefon")
                    @Html.TextBoxFor(x => x.tel, new { @class = "form-control" })
                    <br />
                    @Html.Label("Mail")
                    @Html.TextBoxFor(x => x.mail, new { @class = "form-control" })
                    <br />
                    <button class="btn btn-success">Güncelle</button>
                </div>
            }