MezunBilgiSistemiBitirme/Controllers/BolumController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MezunBilgiSistemiBitirme.Controllers
{
    public class BolumController : Controller
    {
        BolumManager bm = new BolumManager(new EfBolumDal());
        FakulteManager fm = new FakulteManager(new EfFakulteDal());

        public ActionResult Index()
        {
            var BolumValues = bm.GetList();
            return View(BolumValues);
        }
        [HttpGet]
        public ActionResult AddBolum()
        {
            List<SelectListItem> valueFakulte = (from x in fm.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.ad,
                                                     Value = x.fakulteId.ToString(),
                                                 }).ToList();
            ViewBag.vlf = valueFakulte;
            return View();
        }
        [HttpPost]
        public ActionResult AddBolum(Bolum p)
        {
            BolumValidator bolumValidator = new BolumValidator();
            ValidationResult results = bolumValidator.Validate(p);
            if (results.IsValid)
            {
                bm.BolumAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult DeleteBolum(int id)
        {
            var bolumValue = bm.GetById(id);
            bm.BolumDelete(bolumValue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UpdateBolum(int id)
        {
            List<SelectListItem> valueFakulte = (from x in fm.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.ad,
                                                     Value = x.fakulteId.ToString(),
                                                 }).ToList();
            ViewBag.vlf = valueFakulte;
            var bolumValue = bm.GetById(id);
            return View(bolumValue);
        }

        [HttpPost]
        public ActionResult UpdateBolum(Bolum p)
        {
            bm.BolumUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

MezunBilgiSistemiBitirme/Views/Bolum/AddBolum.cshtml
@model EntityLayer.Concrete.Bolum
@{
    ViewBag.Title = "AddBolum";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Bölüm Ekleme</h2>
<br />
@using (Html.BeginForm("AddBolum", "Bolum", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Fakülte")
        @Html.DropDownListFor(x=>x.fakulteId,(List<SelectListItem>)ViewBag.vlf, new { @class = "form-control" })
        <br /><br />
        @Html.Label("Bölüm Adı")
        @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ad)
        <br /><br />
        @Html.Label("Adres")
        @Html.TextBoxFor(x => x.adres, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.adres)
        <br /><br />
        @Html.Label("Telefon")
        @Html.TextBoxFor(x => x.tel, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.tel)
        <br /><br />
        @Html.Label("Mail")
        @Html.TextBoxFor(x => x.mail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.mail)
        <br /><br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

MezunBilgiSistemiBitirme/Views/Bolum/Index.cshtml
@using EntityLayer.Concrete
@model List<EntityLayer.Concrete.Bolum>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Bölüm</h2>
<br />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Bölüm Adı</th>
        <th>Fakülte</th>
        <th>Bölüm Adresi</th>
        <th>Bölüm Telefonu</th>
        <th>Mail</th>
        <th>Sil</th>
        <th>Güncelle</th>
        @*<th>Mezunlar</th>*@
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.bolumId</th>
            <td>@item.ad</td>
            <td>@item.Fakulte.ad</td>
            <td>@item.adres</td>
            <td>@item.tel</td>
            <td>@item.mail</td>
            <td><a href="/Bolum/DeleteBolum/@item.bolumId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Bolum/UpdateBolum/@item.bolumId" class="btn btn-warning">Güncelle</a></td>
            @*<td><a href="#" class="btn btn-primary">Mezunlar</a></td>*@
        </tr>
    }
</table>
<br />
<a href="/Bolum/AddBolum" class="btn btn-info">Yeni Bölüm</a>

MezunBilgiSistemiBitirme/Views/Bolum/UpdateBolum.cshtml
@model EntityLayer.Concrete.Bolum

@{
    ViewBag.Title = "UpdateBolum";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Bölüm Güncelleme</h2>
@using (Html.BeginForm("UpdateBolum", "Bolum", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("ID")
        @Html.TextBoxFor(x => x.bolumId, new { @class = "form-control" })
        <br />
        @Html.Label("Fakülte")
        @Html.DropDownListFor(x => x.fakulteId, (List<SelectListItem>)ViewBag.vlf, new { @class = "form-control" })
        <br /><br />
        @Html.Label("Bölüm Adı")
        @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
        <br />
        @Html.Label("Adres")
        @Html.TextBoxFor(x => x.adres, new { @class = "form-control" })
        <br />
        @Html.Label("Telefon")
        @Html.TextBoxFor(x => x.tel, new { @class = "form-control" })
        <br />
        @Html.Label("Mail")
        @Html.TextBoxFor(x => x.mail, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}