MezunBilgiSistemiBitirme/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MezunBilgiSistemiBitirme.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Test()
        {
            return View();
        }
    }
}

MezunBilgiSistemiBitirme/Controllers/MezunController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace MezunBilgiSistemiBitirme.Controllers
{
    public class MezunController : Controller
    {
        MezunManager mm = new MezunManager(new EfMezunDal());
        BolumManager bm = new BolumManager(new EfBolumDal());
        FakulteManager fm = new FakulteManager(new EfFakulteDal());

        public ActionResult Index()
        {
            var MezunValues = mm.GetList();
            return View(MezunValues);
        }
        public ActionResult Home()
        {
            var MezunValues = mm.GetList();
            var BolumValues = bm.GetList();
            var FakulteValues = fm.GetList();
            return View(MezunValues);
            return View(BolumValues);
            return View(FakulteValues);
        }
        [HttpGet]
        public ActionResult AddMezun()
        {
            
            List<SelectListItem> valueBolum = (from x in bm.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.ad,
                                                     Value = x.bolumId.ToString(),
                                                 }).ToList();
            ViewBag.vlb = valueBolum;
                
            return View();
        }
        [HttpPost]
        public ActionResult AddMezun(Mezun p)
        {
            MezunValidator mezunValidator = new MezunValidator();
            ValidationResult results = mezunValidator.Validate(p);
            if (results.IsValid)
            {
                mm.MezunAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult DeleteMezun(int id)
        {
            var mezunValue = mm.GetById(id);
            mm.MezunDelete(mezunValue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UpdateMezun(int id)
        {

            List<SelectListItem> valueBolum = (from x in bm.GetList()
                                               select new SelectListItem
                                               {
                                                   Text = x.ad,
                                                   Value = x.bolumId.ToString(),
                                               }).ToList();
            ViewBag.vlb = valueBolum;

            var mezunValue = mm.GetById(id);
            return View(mezunValue);
        }

        [HttpPost]
        public ActionResult UpdateMezun(Mezun p)
        {
            mm.MezunUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

MezunBilgiSistemiBitirme/Views/Mezun/AddMezun.cshtml
@model EntityLayer.Mezun
@{
    ViewBag.Title = "AddMezun";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Mezun Ekleme</h2>
<br />
@using (Html.BeginForm("AddMezun", "Mezun", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.Label("Adı Soyadı")
                    @Html.TextBoxFor(x => x.adSoyad, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.adSoyad)
                    <br />
                    @Html.Label("Adresi")
                    @Html.TextBoxFor(x => x.adres, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.adres)
                    <br />
                    @Html.Label("Telefonu")
                    @Html.TextBoxFor(x => x.tel, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.tel)
                    <br />
                    @Html.Label("Maili")
                    @Html.TextBoxFor(x => x.mail, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.mail)
                    <br />
                    @Html.Label("Doğum Tarihi")
                    @Html.TextBoxFor(x => x.dogumTarih, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.dogumTarih)
                    <br />
                    @Html.Label("Öğrenci No")
                    @Html.TextBoxFor(x => x.ogrNo, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.ogrNo)
                    <br />
                    @Html.Label("Yabancı Dil")
                    @Html.TextBoxFor(x => x.yabanciDil, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.yabanciDil)
                    <br />
                    @Html.Label("Bölüm")
                    @Html.DropDownListFor(x => x.bolumId, (List<SelectListItem>)ViewBag.vlb, new { @class = "form-control" })
                    <br />
                    @Html.Label("Başlangıç Yılı")
                    @Html.TextBoxFor(x => x.baslangicYil, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.baslangicYil)
                    <br />
                    @Html.Label("Bitiş Yılı")
                    @Html.TextBoxFor(x => x.bitisYil, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.bitisYil)
                    <br />
                    @Html.Label("Ortalama")
                    @Html.TextBoxFor(x => x.ortalama, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.ortalama)
                    <br />
                    @Html.Label("İlgi Alanı")
                    @Html.TextBoxFor(x => x.ilgiAlan, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.ilgiAlan)
                    <br />
                    @Html.Label("Staj Yeri")
                    @Html.TextBoxFor(x => x.stajYer, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.stajYer)
                    <br />
                    <button class="btn btn-info">Mezun Ekle</button>
                </div>
            }

MezunBilgiSistemiBitirme/Views/Mezun/Home.cshtml
@using EntityLayer.Concrete
@model List<EntityLayer.Mezun>


@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Mezun Bilgi Sistemi'ne Hoşgeldiniz</h2>

<br />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Toplam Mezun Sayısı</th>
        <th>Toplam Bölüm Sayısı</th>
        <th>Toplam Fakülte Sayısı</th>
    </tr>
    @foreach (var item in Model)
    {

    }
    <tr>
        <th> </th>
        <td>@Model.Count()</td>
        <td>@Model.Count()</td>
        <td>@Model.Count()</td>
    </tr>
</table>

MezunBilgiSistemiBitirme/Views/Mezun/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using EntityLayer.Concrete
@model List<EntityLayer.Mezun>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- /.navbar -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mezun Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-header text-muted border-bottom-0">
                                    @item.Bolum.ad
                                </div>
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@item.adSoyad</b></h2>
                                            <p class="text-muted text-sm"><b>İlgi Alanı: </b> @item.ilgiAlan </p>
                                            <p class="text-muted text-sm"><b>Ortalama: </b> @item.ortalama </p>
                                            <p class="text-muted text-sm"><b>Yabancı Dil: </b> @item.yabanciDil </p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Adres: @item.adres</li>
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Telefon: @item.tel</li>
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img src="~/AdminLTE-3.0.4/dist/img/mezun.png" alt="" class="img-circle img-fluid">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="/Mezun/DeleteMezun/@item.mezunId" class="btn btn-sm btn-danger">
                                            <i class="fas fa-trash"></i> Sil
                                        </a>
                                        <a href="/Mezun/UpdateMezun/@item.mezunId" class="btn btn-sm btn-primary">
                                            <i class="fas fa-user"></i> Profili Gör
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
</body>
</html>

<br />
<a href="/Mezun/AddMezun" class="btn btn-info">Yeni Mezun</a>

MezunBilgiSistemiBitirme/Views/Mezun/UpdateMezun.cshtml
@model EntityLayer.Mezun
@{
    ViewBag.Title = "UpdateMezun";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Mezun Güncelleme</h2>
@using (Html.BeginForm("UpdateMezun", "Mezun", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("ID")
        @Html.TextBoxFor(x => x.mezunId, new { @class = "form-control" })
        <br />
        @Html.Label("Adı Soyadı")
        @Html.TextBoxFor(x => x.adSoyad, new { @class = "form-control" })
        <br />
        @Html.Label("Adresi")
        @Html.TextBoxFor(x => x.adres, new { @class = "form-control" })
        <br />
        @Html.Label("Telefonu")
        @Html.TextBoxFor(x => x.tel, new { @class = "form-control" })
        <br />
        @Html.Label("Maili")
        @Html.TextBoxFor(x => x.mail, new { @class = "form-control" })
        <br />
        @Html.Label("Doğum Tarihi")
        @Html.TextBoxFor(x => x.dogumTarih, new { @class = "form-control" })
        <br />
        @Html.Label("Öğrenci No")
        @Html.TextBoxFor(x => x.ogrNo, new { @class = "form-control" })
        <br />
        @Html.Label("Yabancı Dil")
        @Html.TextBoxFor(x => x.yabanciDil, new { @class = "form-control" })
        <br />
        @Html.Label("Bölüm")
        @Html.DropDownListFor(x => x.bolumId, (List<SelectListItem>)ViewBag.vlb, new { @class = "form-control" })
        <br />
        @Html.Label("Başlangıç Yılı")
        @Html.TextBoxFor(x => x.baslangicYil, new { @class = "form-control" })
        <br />
        @Html.Label("Bitiş Yılı")
        @Html.TextBoxFor(x => x.bitisYil, new { @class = "form-control" })
        <br />
        @Html.Label("Ortalama")
        @Html.TextBoxFor(x => x.ortalama, new { @class = "form-control" })
        <br />
        @Html.Label("İlgi Alanı")
        @Html.TextBoxFor(x => x.ilgiAlan, new { @class = "form-control" })
        <br />
        @Html.Label("Staj Yeri")
        @Html.TextBoxFor(x => x.stajYer, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}